# Welcome to Jekyll!
#

# Site settings
title: Andrés Guerrero
description: |
  Design, Marketing, Empowerment
owner: Andrés Guerrero # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: info@andrésguerrero.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.andrésguerrero.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/andresguerrer0
  # github: https://github.com/andresguerrer0
  # linkedin-square: https://linkedin.com/in/andres
  facebook-official: https://www.facebook.com/andresguerreroed
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/andresguerrer0/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
